"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Check,ChevronDown,Code2,Download,Image as ImageIcon,Maximize2,Minus,Plus,RotateCcw,Sparkles} from "lucide-react";
const STARTER=`flowchart LR
  A[Write Mermaid] --> B{Looks good?}
  B -->|Yes| C[Export PNG]
  B -->|Not yet| D[Keep editing]
  D --> A

  style A fill:#eef2ff,stroke:#6366f1
  style C fill:#ecfdf5,stroke:#10b981`;
type Status={kind:"ok"|"error";message:string};
export default function Home(){
 const[source,setSource]=useState(STARTER),[svg,setSvg]=useState(""),[status,setStatus]=useState<Status>({kind:"ok",message:"Diagram rendered successfully"}),[zoom,setZoom]=useState(100),[exportScale,setExportScale]=useState(2);const renderId=useRef(0);
 useEffect(()=>{const timer=window.setTimeout(async()=>{try{const mermaid=(await import("mermaid")).default;mermaid.initialize({startOnLoad:false,theme:"base",securityLevel:"strict",themeVariables:{background:"#ffffff",primaryColor:"#eef2ff",primaryTextColor:"#1f2937",primaryBorderColor:"#6366f1",lineColor:"#64748b",secondaryColor:"#ecfdf5",tertiaryColor:"#f8fafc",fontFamily:"Inter, ui-sans-serif, system-ui, sans-serif"}});const result=await mermaid.render(`mermaid-${++renderId.current}`,source);setSvg(result.svg);setStatus({kind:"ok",message:"Diagram rendered successfully"})}catch(error){setStatus({kind:"error",message:error instanceof Error?error.message.split("\n")[0]:"Invalid Mermaid syntax"})}},350);return()=>window.clearTimeout(timer)},[source]);
 const exportPng=useCallback(()=>{if(!svg)return;const doc=new DOMParser().parseFromString(svg,"image/svg+xml"),node=doc.documentElement,view=node.getAttribute("viewBox")?.split(/\s+/).map(Number),width=view?.[2]||Number(node.getAttribute("width"))||800,height=view?.[3]||Number(node.getAttribute("height"))||600;node.setAttribute("width",String(width));node.setAttribute("height",String(height));const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(node)],{type:"image/svg+xml;charset=utf-8"})),image=new Image();image.onload=()=>{const canvas=document.createElement("canvas");canvas.width=Math.ceil(width*exportScale);canvas.height=Math.ceil(height*exportScale);const context=canvas.getContext("2d");if(!context)return;context.scale(exportScale,exportScale);context.fillStyle="#fff";context.fillRect(0,0,width,height);context.drawImage(image,0,0,width,height);canvas.toBlob(png=>{if(!png)return;const downloadUrl=URL.createObjectURL(png),link=document.createElement("a");link.href=downloadUrl;link.download="mermaid-diagram.png";link.click();URL.revokeObjectURL(downloadUrl)},"image/png");URL.revokeObjectURL(url)};image.src=url},[svg,exportScale]);
 return <main><header className="topbar"><a className="brand" href="#"><span className="brand-mark"><Sparkles size={18}/></span><span>Mermaid <b>Render</b></span></a><div className="header-actions"><span className="saved"><Check size={14}/> Saved locally</span><a href="https://mermaid.js.org/intro/" target="_blank" rel="noreferrer">View Mermaid docs</a></div></header>
 <section className="hero"><p className="eyebrow"><span/> Mermaid to PNG, instantly</p><h1>Turn diagrams into<br/><em>polished PNGs.</em></h1><p>Write Mermaid on the left. See it come alive on the right.<br/> Export when it’s exactly right.</p></section>
 <section className="workspace"><div className="panel editor"><div className="panel-head"><div><i className="lavender"><Code2 size={16}/></i><div><h2>Mermaid code</h2><p>Edits render automatically</p></div></div><button className="reset" onClick={()=>setSource(STARTER)}><RotateCcw size={14}/> Reset</button></div><div className="code-wrap"><div className="lines">{source.split("\n").map((_,i)=><span key={i}>{i+1}</span>)}</div><textarea value={source} onChange={e=>setSource(e.target.value)} spellCheck={false} aria-label="Mermaid diagram source"/></div><div className={`status ${status.kind}`}><span>{status.kind==="ok"?<Check size={13}/>:"!"}</span><p>{status.message}</p></div></div>
 <div className="panel preview"><div className="panel-head"><div><i className="mint"><ImageIcon size={16}/></i><div><h2>Preview</h2><p>Light background · PNG ready</p></div></div><div className="zoom"><button onClick={()=>setZoom(z=>Math.max(50,z-10))}><Minus size={14}/></button><span>{zoom}%</span><button onClick={()=>setZoom(z=>Math.min(180,z+10))}><Plus size={14}/></button><button onClick={()=>setZoom(100)}><Maximize2 size={14}/></button></div></div><div className="canvas"><div className="diagram" style={{transform:`scale(${zoom/100})`}} dangerouslySetInnerHTML={{__html:svg}}/>{!svg&&status.kind==="error"&&<p>Fix the syntax to preview your diagram.</p>}</div><div className="export-bar"><label><span>Export quality</span><div className="select"><select value={exportScale} onChange={e=>setExportScale(Number(e.target.value))}><option value={1}>1× Standard</option><option value={2}>2× High</option><option value={3}>3× Ultra</option></select><ChevronDown size={14}/></div></label><button className="export" onClick={exportPng} disabled={!svg}><Download size={17}/> Export PNG</button></div></div></section><footer><span>Built for clear thinking.</span><span>Nothing leaves your browser.</span></footer></main>}
